gateway:
  host: 0.0.0.0
  port: 8000
  
routes:
  - path: /api/v1/*
    service: service1
    host: localhost:8001
    
  - path: /api/v2/*
    service: service2 
    host: localhost:8002

rate_limits:
  default: 100/hour
